metaflop:
    preview_height: 315

    preview_single:
        generate: gftodvi font.2602gf
        convert_svg: -density 60
        convert_gif: -chop 0x15 -extent 'x{{height}}' -bordercolor white -border 0x{{border_y_offset}} -gravity north -crop 'x{{height}}+0+{{crop_y_offset}}' +repage -flatten

    preview_chart:
        generate: latex -output-format=dvi -jobname=font "\\documentclass[a4paper]{report} \begin{document} \pagestyle{empty} \font\big=font at 22pt \noindent \big \begin{center} \setlength{\tabcolsep}{18pt} \begin{tabular}{ c  c  c  c  c  c  c }  A & B & C & D & E & F & G \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr H & I & J & K & L & M & N \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr  O & P & Q & R & S & T & U  \\  \cr  &   &   &   &   &   &   \\ \cr  &   &   &   &   &   &   \\ \cr  V & W & X & Y & Z   \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr a & b & c & d & e & f & g \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr h & i & j & k & l & m & n \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr o & p & q & r & s & t & u \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr v & w & x & y & z & . & ! \\ \cr   &   &   &   &   &   &   \\ \cr   &   &   &   &   &   &   \\ \cr \end{tabular}  \end{center} \end{document}"

        convert_custom: dvigif -D 200 font.dvi -o font.gif >> /dev/null && convert font.gif -trim +repage -resize 'x{{height}}'

    preview_typewriter:
        generate: latex -output-format=dvi -jobname=font "\\documentclass[a4paper]{report} \begin{document} \pagestyle{empty} \font\big=font at 20pt \noindent \big \begin{flushleft}{{text}} \end{flushleft} \end{document}"

        convert_custom: dvigif -D 200 font.dvi -o font.gif >> /dev/null && convert font.gif -trim +repage -resize '675'

    font_otf: 'perl mf2pt1.pl --comment="Copyright (C) 2012 by Metaflop - Simon Egli, Marco Mueller. http://www.metaflop.com. All rights reserved. License: A copy of the End-User License Agreement to this font software can be found online at http://www.metaflop.com." --family={{fontface}} --nofixedpitch --fullname="{{fontface}} {{font_hash}}" --name="{{fontface}}-{{font_hash}}" --weight={{font_hash}} font.mf'

    glyph_categories:
        - !ruby/symbol cap # A
        - !ruby/symbol cap # B
        - !ruby/symbol capo # C
        - !ruby/symbol cap # D
        - !ruby/symbol cap # E
        - !ruby/symbol cap # F
        - !ruby/symbol capo # G
        - !ruby/symbol cap # H
        - !ruby/symbol cap # I
        - !ruby/symbol cap # J
        - !ruby/symbol cap # K
        - !ruby/symbol cap # L
        - !ruby/symbol cap # M
        - !ruby/symbol cap # N
        - !ruby/symbol capo # O
        - !ruby/symbol cap # P
        - !ruby/symbol capo # Q
        - !ruby/symbol cap # R
        - !ruby/symbol capo # S
        - !ruby/symbol cap # T
        - !ruby/symbol cap # U
        - !ruby/symbol cap # V
        - !ruby/symbol cap # W
        - !ruby/symbol cap # X
        - !ruby/symbol cap # Y
        - !ruby/symbol cap # Z
        - !ruby/symbol meano # a
        - !ruby/symbol asc # b
        - !ruby/symbol meano # c
        - !ruby/symbol asc # d
        - !ruby/symbol meano # e
        - !ruby/symbol asco # f
        - !ruby/symbol meano # g
        - !ruby/symbol asc # h
        - !ruby/symbol asc # i
        - !ruby/symbol asc # j
        - !ruby/symbol asc # k
        - !ruby/symbol asc # l
        - !ruby/symbol meano # m
        - !ruby/symbol meano # n
        - !ruby/symbol meano # o
        - !ruby/symbol meano # p
        - !ruby/symbol meano # q
        - !ruby/symbol meano # r
        - !ruby/symbol meano # s
        - !ruby/symbol asc # t
        - !ruby/symbol mean # u
        - !ruby/symbol mean # v
        - !ruby/symbol mean # w
        - !ruby/symbol mean # x
        - !ruby/symbol mean # y
        - !ruby/symbol mean # z
