version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=metaflop_development
  web:
    build: .
    environment:
      RAILS_ENV: development
    command: bundle exec rackup -o 0.0.0.0 -p 100
    volumes:
      - .:/myapp
    ports:
      - "100:100"
    depends_on:
      - db
